on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Salt Lint Action Demo
    steps:
    - uses: actions/checkout@v1
    - name: Run salt-lint
      uses: roaldnefs/salt-lint-action@master
      env:
        ACTION_STATE_NAME: init.sls
